name: Push Container to Server

on:
  push:
    branches:
      - location

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    

    - name: Create Test Directory
      run: |
       ssh ${{ secrets.DEPLOY_USER }}@${{ secrets.SERVER_HOST }} "cd /home && mkdir test"

