name: Push Container to Server

on:
  push:
    branches:
      - location

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and Push Container
      uses: docker/build-push-action@v2
      with:
        context: ../Dockerfile  # Specify the Dockerfile path (optional)
        push: true
        tags: yuhao10/actiontest:latest

    - name: SSH into Server
      uses: appleboy/ssh-action@master
      with:
        host: "62.72.36.174"
        username: ${{ secrets.DEPLOY_USER }}  # Use a dedicated user (recommended)
        key: ${{ secrets.SERVER_SSH_KEY }}  # Use SSH key for authentication (optional)

    - name: Deploy Container
      run: |
        docker pull yuhao10/actiontest:latest
        docker run -d --name mon -p 3000:3000 yuhao10/actiontest:latest

    - name: Create Test Directory
      run: |
       ssh ${{ secrets.DEPLOY_USER }}@${{ secrets.SERVER_HOST }} "cd /home && mkdir test"

